version: "3.8"

services:

  beacon-ri-tools-v2:
    build:
      context: ./
    container_name: ri-tools
    volumes:
      - ./output_docs:/usr/src/app/output_docs
      - ./datasheets:/usr/src/app/datasheets
      - ./scripts/datasheet/conf:/usr/src/app/scripts/datasheet/conf
      - ./files/vcf/files_to_read:/usr/src/app/files/vcf/files_to_read